name: Backend CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: my_database_7z4p_user
          POSTGRES_PASSWORD: irdDxXIVuOJrPFrVAbRNiW5Aev4O2D32
          POSTGRES_DB: google_drive_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Wait for database
        run: |
          sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for database..."
            sleep 2
          done
      
      - name: Run backend tests
        env:
          FLASK_ENV: testing
          DATABASE_URL: postgresql://my_database_7z4p_user:irdDxXIVuOJrPFrVAbRNiW5Aev4O2D32@localhost:5432/google_drive_db
          PYTHONPATH: ${{ github.workspace }}/server
        run: |
          python -m pytest